# Generated by Django 4.0 on 2021-12-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Marka',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='Model',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='Pojemnośc silnika',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='Rocznik',
            field=models.PositiveSmallIntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Imię',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Nazwisko',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Numer telefonu',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
