# Generated by Django 4.0 on 2021-12-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_marka_alter_car_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='power',
            new_name='Moc (kW)',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_mileage',
            new_name='Przebieg',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='fuel_type',
            new_name='Rodzaj paliwa',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='owner',
            new_name='Właściciel',
        ),
    ]
