# Generated by Django 4.0 on 2021-12-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_power_car_moc (kw)_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Marka',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Moc (kW)',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Numer VIN',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Numer rejestracyjny',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Pojemnośc silnika',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Przebieg',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Rocznik',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Rodzaj paliwa',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Właściciel',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Imię',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Nazwisko',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Numer telefonu',
        ),
        migrations.AddField(
            model_name='car',
            name='brand_model',
            field=models.CharField(max_length=32, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Przebieg'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.CharField(blank=True, default='', max_length=24, null=True, verbose_name='Pojemnośc silnika'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default='', max_length=24, verbose_name='Rodzaj paliwa'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.client', verbose_name='Właściciel'),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.CharField(blank=True, default='', max_length=24, null=True, verbose_name='Moc (kW)'),
        ),
        migrations.AddField(
            model_name='car',
            name='registration_number',
            field=models.CharField(default='', max_length=12, verbose_name='Numer rejestracyjny'),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(default='', max_length=24, verbose_name='Numer VIN'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=2000, null=True, verbose_name='Rocznik'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='client',
            name='firstname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Imię'),
        ),
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Nazwisko'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Numer telefonu'),
        ),
    ]
