# Generated by Django 4.0 on 2021-12-31 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_marka_remove_car_moc (kw)_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Elektryczny'), (0, 'Benzyna'), (3, 'Etanon'), (3, 'Wodór'), (1, 'Benzyna+CNG'), (3, 'Hybryda'), (2, 'Benzyna+LPG'), (3, 'Diesel')], default=0, verbose_name='Rodzaj paliwa'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.client', verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Moc (kW)'),
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Numer rejestracyjny'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=24, null=True, verbose_name='Numer VIN'),
        ),
    ]
