# Generated by Django 4.0 on 2021-12-31 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cars', '0005_alter_car_fuel_type_alter_car_owner_alter_car_power_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'samochód', 'verbose_name_plural': 'Samochody'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'klient', 'verbose_name_plural': 'Klienci'},
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Benzyna'), (1, 'Benzyna+CNG'), (3, 'Elektryczny'), (3, 'Etanol'), (2, 'Benzyna+LPG'), (3, 'Diesel'), (3, 'Wodór'), (3, 'Hybryda')], default=0, verbose_name='Rodzaj paliwa'),
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data przyjęcia ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data naprawy ')),
                ('description', models.TextField(default='', verbose_name='Opis')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Naprawiał')),
            ],
            options={
                'verbose_name': 'naprawa',
                'verbose_name_plural': 'Naprawy',
            },
        ),
    ]
