# Generated by Django 4.0 on 2021-12-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_car_fuel_type_alter_repair_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Benzyna'), (2, 'Benzyna+LPG'), (3, 'Elektryczny'), (3, 'Diesel'), (3, 'Hybryda'), (3, 'Wodór'), (3, 'Etanol'), (1, 'Benzyna+CNG')], default=0, verbose_name='Rodzaj paliwa'),
        ),
    ]
