# Generated by Django 4.0 on 2021-12-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand_model',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Benzyna+LPG'), (1, 'Benzyna+CNG'), (0, 'Benzyna'), (3, 'Wodór'), (3, 'Elektryczny'), (3, 'Hybryda'), (3, 'Diesel'), (3, 'Etanol')], default=0, verbose_name='Rodzaj paliwa'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Opis'),
        ),
    ]
