# Generated by Django 4.0 on 2021-12-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_car_fuel_type_alter_repair_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Benzyna'), (1, 'Benzyna+CNG'), (3, 'Diesel'), (2, 'Benzyna+LPG'), (5, 'Etanol'), (7, 'Wodór'), (4, 'Elektryczny'), (6, 'Hybryda')], default=0, verbose_name='Rodzaj paliwa'),
        ),
    ]
